server:
  listen: 0.0.0.0:4000
  cors:
    origins:
      - https://studio.apollographql.com
subgraphs:
  users:
    routing_url: http://users:4000/graphql
  products:
    routing_url: http://products:4000/graphql
  inventory:
    routing_url: http://inventory:4000/graphql
plugins:
  opentelemetry:
    otlp:
      tracing:
        exporter:
          grpc:
            endpoint: collector:4317
            protocol: Grpc
            timeout: 42
